### ISSUE TITLE
用bee new 创建了项目后，用bee run提示错误

### ISSUE THREAD

**Issue by ywdyy** [beego/bee#240] opened 2016-08-12 03:56 UTC
C:\Go\src\quickstart>bee run
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.3 windows/amd64

2016/08/12 11:54:47 [INFO] Uses 'quickstart' as 'appname'
2016/08/12 11:54:47 [INFO] Initializing watcher...
2016/08/12 11:54:47 [TRAC] Directory(C:\Go\src\quickstart/controllers)
2016/08/12 11:54:47 [TRAC] Directory(C:\Go\src\quickstart)
2016/08/12 11:54:47 [TRAC] Directory(C:\Go\src\quickstart/routers)
2016/08/12 11:54:47 [TRAC] Directory(C:\Go\src\quickstart/tests)
2016/08/12 11:54:47 [INFO] Start building...
can't load package: c:\go\src\quickstart\main.go:5:2: non-standard import "githu
b.com/astaxie/beego" in standard package "quickstart"
c:\go\src\quickstart\controllers\default.go:4:2: non-standard import "github.com
/astaxie/beego" in standard package "quickstart/controllers"
c:\go\src\quickstart\routers\router.go:5:2: non-standard import "github.com/asta
xie/beego" in standard package "quickstart/routers"
2016/08/12 11:54:47 [ERRO] ============== Build failed ===================

C:\Go\src\quickstart>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Go
set GORACE=
set GOROOT=c:\go
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

**Comment by amrfaissal** [comment] 2016-08-12 07:51
The crash is caused by a non-standard import `github.com/astaxie/beego` in standard package `quickstart`. The new go tool enforces that **no standard package** can depend on a non-standard one.

Putting your project `quickstart` directly in `$GOROOT` qualifies it as a standard package, so you cannot depend on non-standard packages such as: `github.com/astaxie/beego`.

**NOTE:** Standard = 'no dots in first path element'.

To fix it, move `$GOPATH\quickstart` to `$GOPATH\github.com\ywdyy\quickstart`.

**Comment by amrfaissal** [comment] 2016-08-15 10:33
@ywdyy this is a friendly ping. Is it working for you? If Yes could you please close this issue.

**Closed** 2016-08-16 12:31 UTC
