### ISSUE TITLE
bee  install  failed

### ISSUE THREAD

**Issue by ybclover** [beego/bee#676] opened 2020-06-23 08:33 UTC
# github.com/gadelkareem/delve/service/debugger
/root/go/src/github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
# github.com/gadelkareem/delve/service/rpccommon
/root/go/src/github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value

**Comment by LNCrafty** [comment] 2020-06-23 09:40
Duplicate of #675

**Comment by LNCrafty** [comment] 2020-06-23 09:41
also see https://github.com/beego/bee/issues/675#issuecomment-647922252 
go get -u github.com/beego/bee@develop

**Comment by askuy** [comment] 2020-06-23 13:48
we fork go-delve/delve, then fix go-delve/delve#2088
so we solve this problem
please use go version > 1.12
export GO111MODULE=on && go get -u github.com/beego/bee

**Closed by askuy** 2020-06-23 13:48 UTC
